### ISSUE TITLE
Project selections not visible

### ISSUE THREAD

**Issue by schmunk42** [jackwu833016/Kimai-chrome#2]
![Bildschirmfoto von 2020-01-15 08-27-46](https://user-images.githubusercontent.com/649031/72413874-13b9d780-3771-11ea-93de-7ca9eb086431.png)

How can I debug this?
Which server version do I need?

**Comment by thejackwu** [comment]
@schmunk42 Sorry for the late reply. What's the bug from that screenshot?

Kimai-chrome is using [v2 API](https://www.kimai.org/documentation/rest-api.html)

**Comment by schmunk42** [comment]
>  What's the bug from that screenshot?

I was not able to select a project, AFAIR.

**Comment by thejackwu** [comment]
Ahha so the **time entries** (The one shown in the screenshot) and **project selection block** are loaded asynchronously. 

```
chrome.storage.sync.get([], function() {
  loadAllTimeEntries(renderTimeEntries, showError);
  loadAllProjectsAndActivities(renderProjectTimerButtons, showError);
});
```
[popup.js](https://github.com/jackwu833016/Kimai-chrome/blob/master/src/js/popup.js)

So my suspicion is that either the project API call is still loading or it fails.
